name: Spring Boot Capstone

on:
  push:
    branches:
      - feature/ksi-jwt

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Start Unit Test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          file: unit-test.Dockerfile
          context: .
          push: true
          tags: dimsen0/capstone-coverage:latest
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: run_test
    steps:
      - run: echo "Start Build Package"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dimsen0/capstone-project:latest
  deployment:
    name: Deploy container using SSH
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - run: echo "Start deploy container"
      - uses: actions/checkout@v3
      - name: Copy environment file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          port: 22
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: .dev.env, .sit.env
          target: /home/${{ secrets.EC2_SSH_USERNAME }}
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          port: 22
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker stop capstone-project capstone-coverage capstone-project-dev
            docker rmi dimsen0/capstone-project:latest dimsen0/capstone-coverage:latest
            docker pull dimsen0/capstone-project:latest
            docker pull dimsen0/capstone-coverage:latest
            docker run -d --rm --name capstone-coverage -p 8000:80 dimsen0/capstone-coverage:latest
            docker run -d --rm --name capstone-project -p 80:8080 --env-file=.dev.env --network capstone_network dimsen0/capstone-project:latest
            docker run -d --rm --name capstone-project-dev -p 8080:8080 --env-file=.sit.env --network capstone_network dimsen0/capstone-project:latest